---
- hosts: all
  become: yes
  vars:

  tasks:
  - name: Install Nginx Web Server on Debian Family
    apt:
      name=nginx
      state=latest
    when:
      ansible_os_family == "Debian"
    notify:
      - nginx systemd

  handlers:
  - name: nginx systemd
    systemd:
     name: nginx.service
     enabled: yes
     state: started
